name = "Hell"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ee71813d9c3dae30c0b2cb139f6aa8be410731543373f569fa21adfdb07a60cf"

[versions]
forge = "47.3.7"
minecraft = "1.20.1"
